---
- name: install tools
  apt: name={{ item }} state=present
  with_items:
    - python-httplib2

- name: install nginx
  apt: name=nginx state=present

- name: configure nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/royalc mode=0644
  notify: restart nginx

- name: get active sites
  shell: ls -1 /etc/nginx/sites-enabled/
  register: active

- name: delete un-needed sites
  file: path=/etc/nginx/sites-enabled/{{ item }} state=absent
  with_items: "{{ active.stdout_lines }}"
  notify: restart nginx 

- name: create symlink sites-site
  file: src=/etc/nginx/sites-available/royalc dest=/etc/nginx/sites-enabled/royalc state=link
  notify: restart nginx

- name: ensure nginx started
  service: name=nginx state=started enabled=yes
